# Generated by Django 4.2.4 on 2023-08-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opanahub', '0002_alter_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
