# Generated by Django 4.2.4 on 2023-08-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opanahub', '0003_alter_posts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='schedule',
        ),
        migrations.AddField(
            model_name='posts',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
