# Generated by Django 4.2.4 on 2023-08-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opanahub', '0004_remove_posts_schedule_posts_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_comment',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
