# Generated by Django 4.2.4 on 2023-08-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opanahub', '0005_like_comment_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_comment',
            name='liked',
        ),
        migrations.AddField(
            model_name='posts',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
