# Generated by Django 4.2.4 on 2023-08-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opanahub', '0006_remove_like_comment_liked_posts_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='sav',
            field=models.BooleanField(default=False),
        ),
    ]
