# Generated by Django 4.2.4 on 2023-08-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opanahub', '0009_accountdeactivation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountDeactivation',
        ),
    ]
